const Icons = {
  add_circle: require('@/assets/icons/add_circle.png'),
  arrow_left: require('@/assets/icons/arrow_left.png'),
  camera: require('@/assets/icons/camera.png'),
  chat: require('@/assets/icons/chat.png'),
  comment: require('@/assets/icons/comment.png'),
  edit_square: require('@/assets/icons/edit_square.png'),
  favorite: require('@/assets/icons/favorite.png'),
  favorite_border: require('@/assets/icons/favorite_border.png'),
  favorite_red: require('@/assets/icons/favorite_red.png'),
  filled_home: require('@/assets/icons/filled_home.png'),
  filled_like: require('@/assets/icons/filled_like.png'),
  filled_profile: require('@/assets/icons/filled_profile.png'),
  filled_reel: require('@/assets/icons/filled_reel.png'),
  filled_search: require('@/assets/icons/filled_search.png'),
  flare: require('@/assets/icons/flare.png'),
  home: require('@/assets/icons/home.png'),
  instagram: require('@/assets/icons/instagram.png'),
  like: require('@/assets/icons/like.png'),
  more_vert: require('@/assets/icons/more_vert.png'),
  post_1: require('@/assets/icons/post_1.png'),
  profile: require('@/assets/icons/profile.png'),
  reel: require('@/assets/icons/reel.png'),
  save: require('@/assets/icons/save.png'),
  search: require('@/assets/icons/search.png'),
  send: require('@/assets/icons/send.png'),
  upload: require('@/assets/icons/upload.png'),
  user_1: require('@/assets/icons/user_1.png'),
  video_call: require('@/assets/icons/video_call.png'),
};

export default Icons;
